version: '3.7'
services:

    postgres:
        restart: always
        container_name: dm_postgres
        build:
            context: .
            dockerfile: Dockerfiles/docker_postgres.conf
        volumes:
            - ../Postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    django:
        restart: always
        container_name: dm_django
        depends_on:
            - postgres
        build:
            context: .
            dockerfile: Dockerfiles/docker_django.conf
        volumes:
            - ./Src:/Src
            - sock-volume:/sock
            - static-volume:/usr/share/nginx/html/static
        network_mode: "host"

    nginx:
        restart: always
        container_name: dm_nginx
        build:
            context: .
            dockerfile: Dockerfiles/docker_nginx.conf
        depends_on:
            - django
        volumes:
            - ./Src:/Src
            - sock-volume:/sock
            - static-volume:/usr/share/nginx/html/static
        ports:
            - "8000:80"

    elasticsearch:
        restart: always
        container_name: dm_elasticsearch
        build:
            context: .
            dockerfile: Dockerfiles/docker_elasticsearch.conf
        depends_on:
            - django
        environment:
            - discovery.type=single-node
        volumes:
            - elasticsearch-volume:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"

    etl_search:
        restart: always
        container_name: dm_etl
        depends_on:
            - postgres
            - elasticsearch
        build:
            context: .
            dockerfile: Dockerfiles/docker_etl.conf
        volumes:
            - ./Src:/Src
            - etl-volume:/var/run/etl
        network_mode: "host"

volumes:
    static-volume:
    sock-volume:
    elasticsearch-volume:
    etl-volume:
