# Generated by Django 3.2.6 on 2021-09-07 11:16

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='genrefilmwork',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 7, 11, 16, 55, 516007), verbose_name='Дата обращения'),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.TextField(choices=[('male', 'мужской'), ('female', 'женский')], null=True, verbose_name='пол'),
        ),
        migrations.AddField(
            model_name='personfilmwork',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 7, 11, 16, 55, 516214), verbose_name='Дата обращения'),
        ),
    ]
