# Generated by Django 3.2.6 on 2021-09-07 11:44

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20210907_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.TextField(blank=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='genrefilmwork',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 7, 11, 44, 46, 989054), verbose_name='Дата обращения'),
        ),
        migrations.AlterField(
            model_name='personfilmwork',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 7, 11, 44, 46, 989256), verbose_name='Дата обращения'),
        ),
    ]
