# Generated by Django 3.2.6 on 2021-09-07 12:00

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20210907_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genrefilmwork',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 7, 12, 0, 2, 847286), verbose_name='Дата обращения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.TextField(blank=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='personfilmwork',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 7, 12, 0, 2, 847494), verbose_name='Дата обращения'),
        ),
    ]
