# Generated by Django 3.2.6 on 2021-09-07 12:02

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20210907_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='person_name',
        ),
        migrations.AlterField(
            model_name='genrefilmwork',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 7, 12, 2, 24, 774404), verbose_name='Дата обращения'),
        ),
        migrations.AlterField(
            model_name='personfilmwork',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 7, 12, 2, 24, 774623), verbose_name='Дата обращения'),
        ),
    ]
