# Generated by Django 3.2.6 on 2021-09-07 12:05

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20210907_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='person_name',
        ),
        migrations.AlterField(
            model_name='genrefilmwork',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 7, 12, 5, 35, 843449), verbose_name='Дата обращения'),
        ),
        migrations.AlterField(
            model_name='personfilmwork',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 7, 12, 5, 35, 843656), verbose_name='Дата обращения'),
        ),
    ]
