# Generated by Django 3.2.6 on 2021-09-07 12:06

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20210907_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_name',
            field=models.TextField(blank=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='genrefilmwork',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 7, 12, 6, 10, 239952), verbose_name='Дата обращения'),
        ),
        migrations.AlterField(
            model_name='personfilmwork',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 7, 12, 6, 10, 240119), verbose_name='Дата обращения'),
        ),
    ]
