# Generated by Django 3.2.6 on 2021-09-07 12:19

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20210907_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genrefilmwork',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 7, 12, 19, 52, 655514), verbose_name='Дата обращения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_name',
            field=models.CharField(max_length=50, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='personfilmwork',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 7, 12, 19, 52, 655682), verbose_name='Дата обращения'),
        ),
    ]
