# Generated by Django 3.2.6 on 2021-09-07 12:23

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20210907_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genrefilmwork',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 7, 12, 23, 13, 589698), verbose_name='Дата обращения'),
        ),
        migrations.AlterField(
            model_name='personfilmwork',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 7, 12, 23, 13, 589918), verbose_name='Дата обращения'),
        ),
    ]
