# Generated by Django 3.2.7 on 2021-10-08 06:16

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20210907_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='personfilmwork',
            name='worktype',
            field=models.CharField(choices=[('actor', 'actor'), ('director', 'director'), ('writer', 'writer'), ('other', 'other')], default='other', max_length=30, verbose_name='Тип участия'),
        ),
        migrations.AlterField(
            model_name='genrefilmwork',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 8, 6, 16, 56, 700053), verbose_name='Дата обращения'),
        ),
        migrations.AlterField(
            model_name='personfilmwork',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 8, 6, 16, 56, 701029), verbose_name='Дата обращения'),
        ),
    ]
