# Generated by Django 3.2.7 on 2021-10-18 16:02

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_distinguish_actors_directors_writers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmwork',
            old_name='person',
            new_name='persons',
        ),
        migrations.AlterField(
            model_name='genrefilmwork',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 18, 16, 2, 12, 361558), verbose_name='Дата обращения'),
        ),
        migrations.AlterField(
            model_name='personfilmwork',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 18, 16, 2, 12, 362488), verbose_name='Дата обращения'),
        ),
    ]
