# Generated by Django 3.2.7 on 2021-11-11 16:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_timestamped_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmwork',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filmwork',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
